### ISSUE TITLE
Can't clone repository to local (github desktop/git)

### ISSUE THREAD

**Issue by dr-nefardio3058** [jge162/create-release#100]
### Hi Jeremy 👋 , 

I tried to **clone this repository** to make some **changes** but it won't let me as it's **stuck** in **822/8644.**

_Can you clone this repo? Any suggestions? I can clone anything but this repository._

**Screenshots:**

![image](https://user-images.githubusercontent.com/124001513/222984119-30826b38-f887-4b12-a1bd-072067373fcd.png)
![image](https://user-images.githubusercontent.com/124001513/222984125-1b6488a5-b319-4216-9904-b2d7d907b97b.png)

> Thanks! 🐱

**Comment by jge162** [comment]
Hello @dr-nefardio3058 you should be able to clone the repo. 

- no branch protection rules exist.
- repo is not set to private but public.
- no SSH Restrictions exist either.
- also no IP address restrictions.
- I was able to clone with no issues previously using GitHub desktop app. Maybe try using GitHub desktop app. 

Not sure why it’s failing. But, keep me posted. Thanks.

**Comment by dr-nefardio3058** [comment]
**It's stuck.**

![image](https://user-images.githubusercontent.com/124001513/223230335-a621fe29-bffe-4ee4-80de-2587b90d128b.png)

**Comment by jge162** [comment]
I’ll try and clone today and see what happens. With git clone and using GitHub desktop app. Keep u posted.

**Comment by dr-nefardio3058** [comment]
> I’ll try and clone today and see what happens. With git clone and using GitHub desktop app. Keep u posted.

Thanks I wanna do some PR's it's stuck.

**Comment by jge162** [comment]
![image](https://user-images.githubusercontent.com/31228460/223285260-317266eb-53c4-4abf-b285-8924c6404d45.png)

git clone worked fine on my linux computer. @dr-nefardio3058 

Will test desktop app on my mac next.

**Comment by jge162** [comment]
It also cloned fine with GitHub desktop app.

**Comment by jge162** [comment]
On your Linux machine maybe delete the directory and retry again.

**Comment by dr-nefardio3058** [comment]
I don't know why it is stuck. I'm on windows btw.

**Comment by jge162** [comment]
Hm try deleting the directory. And then git clone again.
